//
//  BookInformation.swift
//  BookToYou
//
//  Created by ROLF J. on 4/16/24.
//

import Foundation

public struct BookInfo: Hashable {
    var bookId: Int
    var imageName: String
    var title: String
    var author: String
    var genre: String
    var country: String
    var description: String
    var published: String
    var currentStatus: CurrentBookNumberManager.BookStatus
}

public struct BookSeries: Hashable {
    var title: String
    var bookInfo: [BookInfo]
}

let genreList: [String:String] = ["horror":"공포", "thriller":"스릴러", "action":"액션", "wuxia":"무협", "sfFantasy":"SF/판타지"]

class HomeBookCollection {
    
    struct BookInfo: Hashable {
        var bookId: Int
        var imageName: String
        var title: String
        var author: String
        var genre: String
        var country: String
        var description: String
        var published: String
        let identifier: UUID = UUID()
        func hash(into hasher: inout Hasher) {
            hasher.combine(identifier)
        }
    }

    struct BookSeries: Hashable {
        var title: String
        var books: [BookInfo]
        let identifier: UUID = UUID()
        func hash(into hasher: inout Hasher) {
            hasher.combine(identifier)
        }
    }
    
    var collections: [BookSeries] {
        return _collections
    }
    
    fileprivate var _collections = [BookSeries]()
    
    init() {
        generateHomeBooksCollection()
    }
}

extension HomeBookCollection {
    func generateHomeBooksCollection() {
        _collections = [
            BookSeries(title: "😬 진격의 거인", books: [BookInfo(bookId: 20001, imageName: "진격의 거인-01", title: "진격의 거인 1화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "거인이 모든 것을 지배하는 세계.\n거인의 먹이가 되어 버린 인류는 거대한 벽을 쌓고\n벽 바깥으로 나가는 자유와 맞바꿔 침략을 막고 있었다.\n그러나 허울뿐인 평화는 벽을 넘어 버리는\n대거인의 등장으로 무너지고,\n절망적인 싸움이 시작되고 만다.", published: "2014년 8월 7일"),
BookInfo(bookId: 20002, imageName: "진격의 거인-02", title: "진격의 거인 2화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "거인이 지배하는 세계.\n아직 보지 못한 벽 바깥의 세계를 동경하는 엘런은\n훈련병이 되어 동료들과 함께 거인에 대항할 기술을 갈고닦는다.\n그러나 대거인의 등장으로 무수히 \n은 거인이 벽 안으로 침입.\n절친한 친구 아르민을 구하려던 엘런은\n그를 대신해 거인에게 잡아먹힌다…!!", published: "2014년 8월 7일"),
BookInfo(bookId: 20003, imageName: "진격의 거인-03", title: "진격의 거인 3화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "대형거인의 등장으로 벽이 붕괴되고, 무수히 많은 거인이 벽 안쪽으로 침입한다.\n미카사는 계속해서 거인을 쓰러뜨리지만, 엘런의 죽음을 알고 동요돼 위기에 빠지고 만다.\n그때 거인을 공격하는 의문의 거인이 나타나 미카사를 궁지에서 구해낸다.\n몇 구의 거인을 무찌르고 마침내 힘이 다한 의문의 거인.\n그 정체는?!!", published: "2014년 8월 7일"),
BookInfo(bookId: 20004, imageName: "진격의 거인-04", title: "진격의 거인 4화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "월 로제의 외벽에 뚫린 구멍을 막기 위해 ‘거인이 된 엘런이 거대한 바위로 구멍을 막는다’는 작전이 시작된다.\n인류의 존망을 걸고 거인으로 변한 엘런.\n그러나 자아를 잃고 폭주해 버린다.\n엘런은 아르민의 필사적인 질문에도 반응하지 않는데….", published: "2014년 8월 7일"),
BookInfo(bookId: 20005, imageName: "진격의 거인-05", title: "진격의 거인 5화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "거인이 된 엘런의 활약으로 인류는 월 로제의 트로스트 구 탈환에 성공한다.\n성공과 동시에 의식을 잃은 엘런이 눈을 뜨자 그곳에는 조사병단 단장 엘빈 스미스의 모습이.\n엘빈은 거인의 수수께끼가 잠들어 있는 엘런의 생가를 조사하기로 결심한다.\n그러기 위해서는 엘런의 힘이 필요하다고 하는데….", published: "2014년 8월 7일"),
BookInfo(bookId: 20006, imageName: "진격의 거인-06", title: "진격의 거인 6화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "엘런의 생가에 잠들어 있는\n‘거인의 수수께끼’를 알아내기 위해\n벽 바깥 조사를 나온 조사병단.\n거기에는 아르민과 미카사네의 모습도 보인다.", published: "2014년 8월 8일"),
BookInfo(bookId: 20007, imageName: "진격의 거인-07", title: "진격의 거인 7화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "엘런의 생가에 잠자고 있는 ‘거인의 수수께끼’를 찾아 벽 외 조사를 나선 조사병단.\n그 앞에 지성을 가진 ‘여성형 거인’이 나타났다.\n병단을 전멸 위기에 빠뜨리면서도 ‘여성형 거인’을 잡은 엘빈은 여성형 거인의 정체를 밝혀내려고 하는데….", published: "2014년 8월 8일"),
BookInfo(bookId: 20008, imageName: "진격의 거인-08", title: "진격의 거인 8화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "리바이 반의 동료를 잃은 엘런은\n‘여성형 거인’과 싸우지만 패배.\n황급히 달려온 미카사와 리바이의 도움으로 구출되지만,\n‘여성형 거인’을 포획하는 것은 실패하고 만다.", published: "2014년 8월 7일"),
BookInfo(bookId: 20009, imageName: "진격의 거인-09", title: "진격의 거인 9화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "마침내 ‘여성형 거인’을 잡는 것에\n성공한 엘런과 조사병단.\n그러가 때를 같이 하여.\n벽 안에서 잠자는 ‘새로운 수수께끼’에 직면한다.", published: "2014년 8월 7일"),
BookInfo(bookId: 20010, imageName: "진격의 거인-10", title: "진격의 거인 10화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "월 로제 부근에 갑자기 나타난 거인의 무리.\n104기 멤버들을 포함한 조사병단은 거인의 발생 지점을 알아내고자 서둘던 중.\n로제 부근의 우트가르드 성에서 밤을 보내게 된다.\n그러나 밤에는 활동할 수 없는 거인이 성을 에워싸고...!", published: "2014년 8월 7일"),
BookInfo(bookId: 20011, imageName: "진격의 거인-11", title: "진격의 거인 11화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2014년 8월 12일"),
BookInfo(bookId: 20012, imageName: "진격의 거인-12", title: "진격의 거인 12화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2015년 1월 29일"),
BookInfo(bookId: 20013, imageName: "진격의 거인-13", title: "진격의 거인 13화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2016년 1월 26일"),
BookInfo(bookId: 20014, imageName: "진격의 거인-14", title: "진격의 거인 14화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2016년 1월 26일"),
BookInfo(bookId: 20015, imageName: "진격의 거인-15", title: "진격의 거인 15화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2016년 7월 11일"),
BookInfo(bookId: 20016, imageName: "진격의 거인-16", title: "진격의 거인 16화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2016년 8월 8일"),
BookInfo(bookId: 20017, imageName: "진격의 거인-17", title: "진격의 거인 17화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2016년 8월 29일"),
BookInfo(bookId: 20018, imageName: "진격의 거인-18", title: "진격의 거인 18화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2017년 1월 23일"),
BookInfo(bookId: 20019, imageName: "진격의 거인-19", title: "진격의 거인 19화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2017년 4월 10일"),
BookInfo(bookId: 20020, imageName: "진격의 거인-20", title: "진격의 거인 20화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2017년 4월 24일"),
BookInfo(bookId: 20021, imageName: "진격의 거인-21", title: "진격의 거인 21화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2017년 6월 26일"),
BookInfo(bookId: 20022, imageName: "진격의 거인-22", title: "진격의 거인 22화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2017년 8월 14일"),
BookInfo(bookId: 20023, imageName: "진격의 거인-23", title: "진격의 거인 23화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2017년 11월 24일"),
BookInfo(bookId: 20024, imageName: "진격의 거인-24", title: "진격의 거인 24화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2018년 4월 5일"),
BookInfo(bookId: 20025, imageName: "진격의 거인-25", title: "진격의 거인 25화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2018년 7월 19일"),
BookInfo(bookId: 20026, imageName: "진격의 거인-26", title: "진격의 거인 26화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2018년 10월 25일"),
BookInfo(bookId: 20027, imageName: "진격의 거인-27", title: "진격의 거인 27화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2019년 2월 20일"),
BookInfo(bookId: 20028, imageName: "진격의 거인-28", title: "진격의 거인 28화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2019년 7월 17일"),
BookInfo(bookId: 20029, imageName: "진격의 거인-29", title: "진격의 거인 29화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2020년 2월 20일"),
BookInfo(bookId: 20030, imageName: "진격의 거인-30", title: "진격의 거인 30화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2020년 4월 15일"),
BookInfo(bookId: 20031, imageName: "진격의 거인-31", title: "진격의 거인 31화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2020년 7월 28일"),
BookInfo(bookId: 20032, imageName: "진격의 거인-32", title: "진격의 거인 32화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2021년 1월 22일"),
BookInfo(bookId: 20033, imageName: "진격의 거인-33", title: "진격의 거인 33화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2021년 4월 9일"),
BookInfo(bookId: 20034, imageName: "진격의 거인-34", title: "진격의 거인 34화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2021년 11월 19일")
              ]),
            BookSeries(title: "🌺 화산귀환", books: [BookInfo(bookId: 10001, imageName: "화산귀환-01", title: "화산귀환 1화", author: "작가 ✍️ STUDIO LICO 저자(글) · 비가 원작", genre: "장르 🎬 \(genreList["wuxia"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "대 화산파 13대 제자. 천하삼대검수 매화검존 청명.\n천하를 혼란에 빠뜨린 고금제일마 천마의 목을 치고 십만대산의 정상에서 영면.\n백 년의 시간을 뛰어넘어 아이의 몸으로 다시 살아나다.\n……뭐? 화산이 망해? 이게 뭔 개소리야!?", published: "2023년 1월 18일"),
  BookInfo(bookId: 10002, imageName: "화산귀환-02", title: "화산귀환 2화", author: "작가 ✍️ STUDIO LICO 저자(글) · 비가 원작", genre: "장르 🎬 \(genreList["wuxia"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "대 화산파 13대 제자. 천하삼대검수 매화검존 청명.\n천하를 혼란에 빠뜨린 고금제일마 천마의 목을 치고 십만대산의 정상에서 영면.\n백 년의 시간을 뛰어넘어 아이의 몸으로 다시 살아나다.\n……뭐? 화산이 망해? 이게 뭔 개소리야!?", published: "2023년 1월 18일"),
  BookInfo(bookId: 10003, imageName: "화산귀환-03", title: "화산귀환 3화", author: "작가 ✍️ STUDIO LICO 저자(글) · 비가 원작", genre: "장르 🎬 \(genreList["wuxia"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "대 화산파 13대 제자. 천하삼대검수 매화검존 청명.\n천하를 혼란에 빠뜨린 고금제일마 천마의 목을 치고 십만대산의 정상에서 영면.\n백 년의 시간을 뛰어넘어 아이의 몸으로 다시 살아나다.\n……뭐? 화산이 망해? 이게 뭔 개소리야!?", published: "2023년 5월 10일"),
  BookInfo(bookId: 10004, imageName: "화산귀환-04", title: "화산귀환 4화", author: "작가 ✍️ STUDIO LICO 저자(글) · 비가 원작", genre: "장르 🎬 \(genreList["wuxia"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "대 화산파 13대 제자. 천하삼대검수 매화검존 청명.\n천하를 혼란에 빠뜨린 고금제일마 천마의 목을 치고 십만대산의 정상에서 영면.\n백 년의 시간을 뛰어넘어 아이의 몸으로 다시 살아나다.\n……뭐? 화산이 망해? 이게 뭔 개소리야!?", published: "2023년 8월 29일"),
  BookInfo(bookId: 10005, imageName: "화산귀환-05", title: "화산귀환 5화", author: "작가 ✍️ STUDIO LICO 저자(글) · 비가 원작", genre: "장르 🎬 \(genreList["wuxia"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "대 화산파 13대 제자. 천하삼대검수 매화검존 청명.\n천하를 혼란에 빠뜨린 고금제일마 천마의 목을 치고 십만대산의 정상에서 영면.\n백 년의 시간을 뛰어넘어 아이의 몸으로 다시 살아나다.\n……뭐? 화산이 망해? 이게 뭔 개소리야!?", published: "2024년 2월 22일")
            ]),
            BookSeries(title: "🔥 나 혼자만 레벨업", books: [BookInfo(bookId: 10006, imageName: "나 혼자만 레벨업-01", title: "나 혼자만 레벨업 1화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2019년 9월 26일"),
BookInfo(bookId: 10007, imageName: "나 혼자만 레벨업-02", title: "나 혼자만 레벨업 2화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2020년 1월 30일"),
BookInfo(bookId: 10008, imageName: "나 혼자만 레벨업-03", title: "나 혼자만 레벨업 3화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2020년 8월 27일"),
BookInfo(bookId: 10009, imageName: "나 혼자만 레벨업-04", title: "나 혼자만 레벨업 4화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2021년 4월 29일"),
BookInfo(bookId: 10010, imageName: "나 혼자만 레벨업-05", title: "나 혼자만 레벨업 5화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2021년 10월 7일"),
BookInfo(bookId: 10011, imageName: "나 혼자만 레벨업-06", title: "나 혼자만 레벨업 6화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2022년 7월 25일"),
BookInfo(bookId: 10012, imageName: "나 혼자만 레벨업-07", title: "나 혼자만 레벨업 7화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2023년 2월 22일"),
BookInfo(bookId: 10013, imageName: "나 혼자만 레벨업-08", title: "나 혼자만 레벨업 8화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2023년 5월 25일"),
BookInfo(bookId: 10014, imageName: "나 혼자만 레벨업-09", title: "나 혼자만 레벨업 9화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2024년 2월 29일"),
BookInfo(bookId: 10015, imageName: "나 혼자만 레벨업-10", title: "나 혼자만 레벨업 10화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2024년 4월 18일")
            ])
        ]
    }
}



let allBookList: [BookInfo] = [
    BookInfo(bookId: 20001, imageName: "진격의 거인-01", title: "진격의 거인 1화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "거인이 모든 것을 지배하는 세계.\n거인의 먹이가 되어 버린 인류는 거대한 벽을 쌓고\n벽 바깥으로 나가는 자유와 맞바꿔 침략을 막고 있었다.\n그러나 허울뿐인 평화는 벽을 넘어 버리는\n대거인의 등장으로 무너지고,\n절망적인 싸움이 시작되고 만다.", published: "2014년 8월 7일", currentStatus: .normal),
    BookInfo(bookId: 20002, imageName: "진격의 거인-02", title: "진격의 거인 2화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "거인이 지배하는 세계.\n아직 보지 못한 벽 바깥의 세계를 동경하는 엘런은\n훈련병이 되어 동료들과 함께 거인에 대항할 기술을 갈고닦는다.\n그러나 대거인의 등장으로 무수히 \n은 거인이 벽 안으로 침입.\n절친한 친구 아르민을 구하려던 엘런은\n그를 대신해 거인에게 잡아먹힌다…!!", published: "2014년 8월 7일", currentStatus: .normal),
    BookInfo(bookId: 20003, imageName: "진격의 거인-03", title: "진격의 거인 3화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "대형거인의 등장으로 벽이 붕괴되고, 무수히 많은 거인이 벽 안쪽으로 침입한다.\n미카사는 계속해서 거인을 쓰러뜨리지만, 엘런의 죽음을 알고 동요돼 위기에 빠지고 만다.\n그때 거인을 공격하는 의문의 거인이 나타나 미카사를 궁지에서 구해낸다.\n몇 구의 거인을 무찌르고 마침내 힘이 다한 의문의 거인.\n그 정체는?!!", published: "2014년 8월 7일", currentStatus: .normal),
    BookInfo(bookId: 20004, imageName: "진격의 거인-04", title: "진격의 거인 4화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "월 로제의 외벽에 뚫린 구멍을 막기 위해 ‘거인이 된 엘런이 거대한 바위로 구멍을 막는다’는 작전이 시작된다.\n인류의 존망을 걸고 거인으로 변한 엘런.\n그러나 자아를 잃고 폭주해 버린다.\n엘런은 아르민의 필사적인 질문에도 반응하지 않는데….", published: "2014년 8월 7일", currentStatus: .normal),
    BookInfo(bookId: 20005, imageName: "진격의 거인-05", title: "진격의 거인 5화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "거인이 된 엘런의 활약으로 인류는 월 로제의 트로스트 구 탈환에 성공한다.\n성공과 동시에 의식을 잃은 엘런이 눈을 뜨자 그곳에는 조사병단 단장 엘빈 스미스의 모습이.\n엘빈은 거인의 수수께끼가 잠들어 있는 엘런의 생가를 조사하기로 결심한다.\n그러기 위해서는 엘런의 힘이 필요하다고 하는데….", published: "2014년 8월 7일", currentStatus: .normal),
    BookInfo(bookId: 20006, imageName: "진격의 거인-06", title: "진격의 거인 6화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "엘런의 생가에 잠들어 있는\n‘거인의 수수께끼’를 알아내기 위해\n벽 바깥 조사를 나온 조사병단.\n거기에는 아르민과 미카사네의 모습도 보인다.", published: "2014년 8월 8일", currentStatus: .normal),
    BookInfo(bookId: 20007, imageName: "진격의 거인-07", title: "진격의 거인 7화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "엘런의 생가에 잠자고 있는 ‘거인의 수수께끼’를 찾아 벽 외 조사를 나선 조사병단.\n그 앞에 지성을 가진 ‘여성형 거인’이 나타났다.\n병단을 전멸 위기에 빠뜨리면서도 ‘여성형 거인’을 잡은 엘빈은 여성형 거인의 정체를 밝혀내려고 하는데….", published: "2014년 8월 8일", currentStatus: .normal),
    BookInfo(bookId: 20008, imageName: "진격의 거인-08", title: "진격의 거인 8화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "리바이 반의 동료를 잃은 엘런은\n‘여성형 거인’과 싸우지만 패배.\n황급히 달려온 미카사와 리바이의 도움으로 구출되지만,\n‘여성형 거인’을 포획하는 것은 실패하고 만다.", published: "2014년 8월 7일", currentStatus: .normal),
    BookInfo(bookId: 20009, imageName: "진격의 거인-09", title: "진격의 거인 9화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "마침내 ‘여성형 거인’을 잡는 것에\n성공한 엘런과 조사병단.\n그러가 때를 같이 하여.\n벽 안에서 잠자는 ‘새로운 수수께끼’에 직면한다.", published: "2014년 8월 7일", currentStatus: .normal),
    BookInfo(bookId: 20010, imageName: "진격의 거인-10", title: "진격의 거인 10화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "월 로제 부근에 갑자기 나타난 거인의 무리.\n104기 멤버들을 포함한 조사병단은 거인의 발생 지점을 알아내고자 서둘던 중.\n로제 부근의 우트가르드 성에서 밤을 보내게 된다.\n그러나 밤에는 활동할 수 없는 거인이 성을 에워싸고...!", published: "2014년 8월 7일", currentStatus: .normal),
    BookInfo(bookId: 20011, imageName: "진격의 거인-11", title: "진격의 거인 11화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2014년 8월 12일", currentStatus: .normal),
    BookInfo(bookId: 20012, imageName: "진격의 거인-12", title: "진격의 거인 12화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2015년 1월 29일", currentStatus: .normal),
    BookInfo(bookId: 20013, imageName: "진격의 거인-13", title: "진격의 거인 13화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2016년 1월 26일", currentStatus: .normal),
    BookInfo(bookId: 20014, imageName: "진격의 거인-14", title: "진격의 거인 14화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2016년 1월 26일", currentStatus: .normal),
    BookInfo(bookId: 20015, imageName: "진격의 거인-15", title: "진격의 거인 15화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2016년 7월 11일", currentStatus: .normal),
    BookInfo(bookId: 20016, imageName: "진격의 거인-16", title: "진격의 거인 16화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2016년 8월 8일", currentStatus: .normal),
    BookInfo(bookId: 20017, imageName: "진격의 거인-17", title: "진격의 거인 17화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2016년 8월 29일", currentStatus: .normal),
    BookInfo(bookId: 20018, imageName: "진격의 거인-18", title: "진격의 거인 18화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2017년 1월 23일", currentStatus: .normal),
    BookInfo(bookId: 20019, imageName: "진격의 거인-19", title: "진격의 거인 19화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2017년 4월 10일", currentStatus: .normal),
    BookInfo(bookId: 20020, imageName: "진격의 거인-20", title: "진격의 거인 20화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2017년 4월 24일", currentStatus: .normal),
    BookInfo(bookId: 20021, imageName: "진격의 거인-21", title: "진격의 거인 21화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2017년 6월 26일", currentStatus: .normal),
    BookInfo(bookId: 20022, imageName: "진격의 거인-22", title: "진격의 거인 22화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2017년 8월 14일", currentStatus: .normal),
    BookInfo(bookId: 20023, imageName: "진격의 거인-23", title: "진격의 거인 23화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2017년 11월 24일", currentStatus: .normal),
    BookInfo(bookId: 20024, imageName: "진격의 거인-24", title: "진격의 거인 24화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2018년 4월 5일", currentStatus: .normal),
    BookInfo(bookId: 20025, imageName: "진격의 거인-25", title: "진격의 거인 25화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2018년 7월 19일", currentStatus: .normal),
    BookInfo(bookId: 20026, imageName: "진격의 거인-26", title: "진격의 거인 26화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2018년 10월 25일", currentStatus: .normal),
    BookInfo(bookId: 20027, imageName: "진격의 거인-27", title: "진격의 거인 27화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2019년 2월 20일", currentStatus: .normal),
    BookInfo(bookId: 20028, imageName: "진격의 거인-28", title: "진격의 거인 28화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2019년 7월 17일", currentStatus: .normal),
    BookInfo(bookId: 20029, imageName: "진격의 거인-29", title: "진격의 거인 29화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2020년 2월 20일", currentStatus: .normal),
    BookInfo(bookId: 20030, imageName: "진격의 거인-30", title: "진격의 거인 30화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2020년 4월 15일", currentStatus: .normal),
    BookInfo(bookId: 20031, imageName: "진격의 거인-31", title: "진격의 거인 31화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2020년 7월 28일", currentStatus: .normal),
    BookInfo(bookId: 20032, imageName: "진격의 거인-32", title: "진격의 거인 32화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2021년 1월 22일", currentStatus: .normal),
    BookInfo(bookId: 20033, imageName: "진격의 거인-33", title: "진격의 거인 33화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2021년 4월 9일", currentStatus: .normal),
    BookInfo(bookId: 20034, imageName: "진격의 거인-34", title: "진격의 거인 34화", author: "작가 ✍️ 이사야마 하지메 글 · 그림", genre: "장르 🎬 \(genreList["horror"] ?? "Error"), \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇯🇵", description: "nan", published: "2021년 11월 19일", currentStatus: .normal),
    BookInfo(bookId: 10001, imageName: "화산귀환-01", title: "화산귀환 1화", author: "작가 ✍️ STUDIO LICO 저자(글) · 비가 원작", genre: "장르 🎬 \(genreList["wuxia"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "대 화산파 13대 제자. 천하삼대검수 매화검존 청명.\n천하를 혼란에 빠뜨린 고금제일마 천마의 목을 치고 십만대산의 정상에서 영면.\n백 년의 시간을 뛰어넘어 아이의 몸으로 다시 살아나다.\n……뭐? 화산이 망해? 이게 뭔 개소리야!?", published: "2023년 1월 18일", currentStatus: .normal),
    BookInfo(bookId: 10002, imageName: "화산귀환-02", title: "화산귀환 2화", author: "작가 ✍️ STUDIO LICO 저자(글) · 비가 원작", genre: "장르 🎬 \(genreList["wuxia"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "대 화산파 13대 제자. 천하삼대검수 매화검존 청명.\n천하를 혼란에 빠뜨린 고금제일마 천마의 목을 치고 십만대산의 정상에서 영면.\n백 년의 시간을 뛰어넘어 아이의 몸으로 다시 살아나다.\n……뭐? 화산이 망해? 이게 뭔 개소리야!?", published: "2023년 1월 18일", currentStatus: .normal),
    BookInfo(bookId: 10003, imageName: "화산귀환-03", title: "화산귀환 3화", author: "작가 ✍️ STUDIO LICO 저자(글) · 비가 원작", genre: "장르 🎬 \(genreList["wuxia"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "대 화산파 13대 제자. 천하삼대검수 매화검존 청명.\n천하를 혼란에 빠뜨린 고금제일마 천마의 목을 치고 십만대산의 정상에서 영면.\n백 년의 시간을 뛰어넘어 아이의 몸으로 다시 살아나다.\n……뭐? 화산이 망해? 이게 뭔 개소리야!?", published: "2023년 5월 10일", currentStatus: .normal),
    BookInfo(bookId: 10004, imageName: "화산귀환-04", title: "화산귀환 4화", author: "작가 ✍️ STUDIO LICO 저자(글) · 비가 원작", genre: "장르 🎬 \(genreList["wuxia"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "대 화산파 13대 제자. 천하삼대검수 매화검존 청명.\n천하를 혼란에 빠뜨린 고금제일마 천마의 목을 치고 십만대산의 정상에서 영면.\n백 년의 시간을 뛰어넘어 아이의 몸으로 다시 살아나다.\n……뭐? 화산이 망해? 이게 뭔 개소리야!?", published: "2023년 8월 29일", currentStatus: .normal),
    BookInfo(bookId: 10005, imageName: "화산귀환-05", title: "화산귀환 5화", author: "작가 ✍️ STUDIO LICO 저자(글) · 비가 원작", genre: "장르 🎬 \(genreList["wuxia"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "대 화산파 13대 제자. 천하삼대검수 매화검존 청명.\n천하를 혼란에 빠뜨린 고금제일마 천마의 목을 치고 십만대산의 정상에서 영면.\n백 년의 시간을 뛰어넘어 아이의 몸으로 다시 살아나다.\n……뭐? 화산이 망해? 이게 뭔 개소리야!?", published: "2024년 2월 22일", currentStatus: .normal),
    BookInfo(bookId: 10006, imageName: "나 혼자만 레벨업-01", title: "나 혼자만 레벨업 1화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2019년 9월 26일", currentStatus: .normal),
    BookInfo(bookId: 10007, imageName: "나 혼자만 레벨업-02", title: "나 혼자만 레벨업 2화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2020년 1월 30일", currentStatus: .normal),
    BookInfo(bookId: 10008, imageName: "나 혼자만 레벨업-03", title: "나 혼자만 레벨업 3화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2020년 8월 27일", currentStatus: .normal),
    BookInfo(bookId: 10009, imageName: "나 혼자만 레벨업-04", title: "나 혼자만 레벨업 4화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2021년 4월 29일", currentStatus: .normal),
    BookInfo(bookId: 10010, imageName: "나 혼자만 레벨업-05", title: "나 혼자만 레벨업 5화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2021년 10월 7일", currentStatus: .normal),
    BookInfo(bookId: 10011, imageName: "나 혼자만 레벨업-06", title: "나 혼자만 레벨업 6화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2022년 7월 25일", currentStatus: .normal),
    BookInfo(bookId: 10012, imageName: "나 혼자만 레벨업-07", title: "나 혼자만 레벨업 7화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2023년 2월 22일", currentStatus: .normal),
    BookInfo(bookId: 10013, imageName: "나 혼자만 레벨업-08", title: "나 혼자만 레벨업 8화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2023년 5월 25일", currentStatus: .normal),
    BookInfo(bookId: 10014, imageName: "나 혼자만 레벨업-09", title: "나 혼자만 레벨업 9화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2024년 2월 29일", currentStatus: .normal),
    BookInfo(bookId: 10015, imageName: "나 혼자만 레벨업-10", title: "나 혼자만 레벨업 10화", author: "작가 ✍️ 장성락 저자(글) · 추공 원작", genre: "장르 🎬 \(genreList["sfFantasy"] ?? "Error"), \(genreList["action"] ?? "Error")", country: "🇰🇷", description: "전 세계 독자가 열광한 레이드 액션의 진수!\n미국, 독일, 프랑스, 브라질, 스페인, 아르헨티나, 덴마크, 스웨덴, 우크라이나,\n포르투갈, 이탈리아, 일본, 태국, 중국을 비롯, 세계 각국에 단행본 수출 중!!\n\n최약체에서 최강 헌터로, 세상의 중심에 서다! 카카오페이지에서 연일 화제를 모으며, 폭발적 인기 속에 연재를 마친 장성락(REDICE STUDIO) 만화, 추공 원작, 현군 각색 『만화 나 혼자만 레벨업』 단행본 10권이 출간된다. 『만화 나 혼자만 레벨업』은 글로벌 플랫폼 웹툰 연재로 세계 각국에 팬덤이 형성될 만큼 완성도와 재미, 콘텐츠로서의 저력을 입증한 작품이다. 또한 압도적인 인기에 힘입어 각국에 단행본 수출 릴레이를 이어가는 중이며, 2024년은 넷플릭스 등 다수의 OTT 채널을 통해 TV애니메이션이 전 세계 동시 방영되었고, 넷마블에서 게임이 론칭되는 등 글로벌 단위의 인기를 실감하게 하는 한 해가 됐다.\n단행본은 본문 전면 재연출을 거쳐 넉넉한 판형으로 출간되어, 모바일 스크롤 웹툰과는 또 다른 ‘나혼렙’ 액션신의 쾌감을 100% 만끽할 수 있다.\n한 화 읽고 나면 정신을 차릴 수 없이 빠져드는 레이드 액션의 진수! 돈 없고, 빽 없고, 능력 없는 사상 최약체 E급 헌터, 성진우의 화려한 부활, 그리고 레벨업이 시작된다!", published: "2024년 4월 18일", currentStatus: .normal)
]
